# Generated by Django 4.2.7 on 2023-11-29 17:39!

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(default='Default Hostel', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Tripple', 'Tripple')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelApp.hostel')),
            ],
        ),
    ]
