# Generated by Django 4.2.7 on 2023-11-29 17:57!

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(default='Olympia Hostel', max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('booked_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostelApp.room')),
            ],
        ),
    ]
